/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

/**
 * A data class for Custom Header Signature credentials.
 */
public class ApiHeaderModel {
    private String token;
    private String apiKey;

    /**
     * A Constructor for ApiHeaderModel.
     */
    private ApiHeaderModel(String token, String apiKey) {
        this.token = token;
        this.apiKey = apiKey;
    }

    /**
     * Getter for token.
     * @return token The value of token.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Getter for apiKey.
     * @return apiKey The value of api-key.
     */
    public String getApiKey() {
        return this.apiKey;
    }

    /**
     * Builds a new {@link ApiHeaderModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link ApiHeaderModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getToken(), getApiKey());
    }

    /**
     * A Builder class for Custom Header Signature credentials.
     */
    public static class Builder {
        private String token;
        private String apiKey;

        /**
         * The constructor with required auth credentials.
         * @param token The value of Token.
         * @param apiKey The value of ApiKey.
         */
        public Builder(String token, String apiKey) {
            if (token == null) {
                throw new NullPointerException("Token cannot be null.");
            }

            if (apiKey == null) {
                throw new NullPointerException("ApiKey cannot be null.");
            }

            this.token = token;
            this.apiKey = apiKey;
        }

        /**
         * Setter for token.
         * @param token The value of token.
         * @return Builder The current instance of Builder.
         */
        public Builder token(String token) {
            if (token == null) {
                throw new NullPointerException("Token cannot be null.");
            }

            this.token = token;
            return this;
        }

        /**
         * Setter for apiKey.
         * @param apiKey The value of api-key.
         * @return Builder The current instance of Builder.
         */
        public Builder apiKey(String apiKey) {
            if (apiKey == null) {
                throw new NullPointerException("ApiKey cannot be null.");
            }

            this.apiKey = apiKey;
            return this;
        }

        /**
         * Builds the instance of ApiHeaderModel using the provided credentials.
         * @return The instance of ApiHeaderModel.
         */
        public ApiHeaderModel build() {
            return new ApiHeaderModel(token, apiKey);
        }
    }
}