/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;

public class ApiHeaderManager extends HeaderAuth implements ApiHeaderCredentials {

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private ApiHeaderModel authModel;

    /**
     * Constructor that sets custom header parameters.
     */
    public ApiHeaderManager(ApiHeaderModel authModel) {

        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("token", authModel.getToken());
                put("api-key", authModel.getApiKey());
            }
        });

        this.authModel = authModel;
    }

    /**
     * String value for token.
     * @return token
     */
    public String getToken() {
        return authModel.getToken();
    }

    /**
     * String value for apiKey.
     * @return apiKey
     */
    public String getApiKey() {
        return authModel.getApiKey();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param token String value for credentials.
     * @param apiKey String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String token, String apiKey) {
        return token.equals(getToken())
                && apiKey.equals(getApiKey());
    }

    /**
     * Converts this ApiHeaderManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ApiHeaderManager [" + "token=" + getToken() + ", apiKey=" + getApiKey() + "]";
    }
    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "ApiHeader - " + errorMessage;
    }

}
