/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

/**
 * Interface for defining the behavior of CustomHeader Authentication.
 */
public interface ApiHeaderCredentials {

    /**
     * String value for token.
     * @return token
     */
    String getToken();

    /**
     * String value for apiKey.
     * @return apiKey
     */
    String getApiKey();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param token String value for credentials.
     * @param apiKey String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String token, String apiKey);
}
