/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;
import localhost3000.Configuration;

public class CustomAuthManager extends HeaderAuth {

    /**
     * Constructor that sets custom auth parameters.
     */
    public CustomAuthManager(Configuration config) {
        super(new HashMap<String, String>(){
            private static final long serialVersionUID = 1L;
            {
                // TODO: Add your custom authentication here
                // The following properties are available to use
                // put("Authorization", config.getAccessToken());
                // put("Key", "Value");
            }
        });

    }

    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "CustomAuth - " + errorMessage;
    }

}
