/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

import io.apimatic.core.GlobalConfiguration;
import io.apimatic.core.authentication.HeaderAuth;
import java.io.IOException;
import java.util.Base64;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import localhost3000.controllers.OAuthAuthorizationController;
import localhost3000.exceptions.ApiException;
import localhost3000.models.OAuthToken;

/**
 * Utility class for OAuth 2 authorization and token management.
 */
public class OAuthROPCGManager extends HeaderAuth implements OAuthROPCGCredentials {

    /**
     * Private instance of OAuth 2 API controller.
     */
    private OAuthAuthorizationController oAuthApi;

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private OAuthROPCGModel authModel;

    /**
     * Constructor.
     */
    public OAuthROPCGManager(OAuthROPCGModel authModel) {
        super(Collections.singletonMap("Authorization",
                getAuthorizationHeader(authModel.getOAuthToken())));
        this.authModel = authModel;
    }

    /**
    * Apply GlobalConfiguration for token management.
    * @param config GlobalConfiguration instance
    */
    public void applyGlobalConfiguration(GlobalConfiguration config) {
        this.oAuthApi = new OAuthAuthorizationController(config);
    }


    /**
     * String value for oAuthClientId.
     * @return oAuthClientId
     */
    public String getOAuthClientId() {
        return authModel.getOAuthClientId();
    }

    /**
     * String value for oAuthClientSecret.
     * @return oAuthClientSecret
     */
    public String getOAuthClientSecret() {
        return authModel.getOAuthClientSecret();
    }

    /**
     * String value for oAuthUsername.
     * @return oAuthUsername
     */
    public String getOAuthUsername() {
        return authModel.getOAuthUsername();
    }

    /**
     * String value for oAuthPassword.
     * @return oAuthPassword
     */
    public String getOAuthPassword() {
        return authModel.getOAuthPassword();
    }

    /**
     * OAuthToken value for oAuthToken.
     * @return oAuthToken
     */
    public OAuthToken getOAuthToken() {
        return authModel.getOAuthToken();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param oAuthClientId String value for credentials.
     * @param oAuthClientSecret String value for credentials.
     * @param oAuthUsername String value for credentials.
     * @param oAuthPassword String value for credentials.
     * @param oAuthToken OAuthToken value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String oAuthClientId, String oAuthClientSecret, String oAuthUsername,
            String oAuthPassword, OAuthToken oAuthToken) {
        return oAuthClientId.equals(getOAuthClientId())
                && oAuthClientSecret.equals(getOAuthClientSecret())
                && oAuthUsername.equals(getOAuthUsername())
                && oAuthPassword.equals(getOAuthPassword())
                && ((getOAuthToken() == null && oAuthToken == null)
                        || (getOAuthToken() != null && oAuthToken != null
                                && oAuthToken.toString().equals(getOAuthToken().toString())));
    }

    /**
     * Converts this OAuthROPCGManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OAuthROPCGManager [" + "oAuthClientId=" + getOAuthClientId()
                + ", oAuthClientSecret=" + getOAuthClientSecret() + ", oAuthUsername="
                + getOAuthUsername() + ", oAuthPassword=" + getOAuthPassword() + ", oAuthToken="
                + getOAuthToken() + "]";
    }

    /**
     * Fetch the OAuth token asynchronously.
     * @param additionalParameters Additional parameters to send during authorization
     */
    public CompletableFuture<OAuthToken> fetchTokenAsync(
            final Map<String, Object> additionalParameters) {
        final Map<String, Object> aparams =
                additionalParameters == null ? new HashMap<String, Object>() : additionalParameters;
        return oAuthApi.requestTokenOAuthROPCGAsync(
            getBasicAuthForClient(),
            getOAuthUsername(),
            getOAuthPassword(),
            null,
            aparams).thenApply(token -> {
                Long expiresIn = token.getExpiresIn();
                if (expiresIn != null && expiresIn != 0) {
                    token.setExpiry((System.currentTimeMillis() / 1000L) + token.getExpiresIn());
                }
                return token;
            });
    }

    /**
     * Fetch the OAuth token asynchronously.
     */
    public CompletableFuture<OAuthToken> fetchTokenAsync() {
        return fetchTokenAsync(null);
    }

    /**
     * Fetch the OAuth token.
     * @param additionalParameters Additional parameters to send during authorization
     */
    public OAuthToken fetchToken(Map<String, Object> additionalParameters)
            throws ApiException, IOException {
        final Map<String, Object> aparams =
                additionalParameters == null ? new HashMap<String, Object>() : additionalParameters;
        OAuthToken token = oAuthApi.requestTokenOAuthROPCG(
            getBasicAuthForClient(),
            getOAuthUsername(),
            getOAuthPassword(),
            null,
            aparams);

        if (token.getExpiresIn() != null && token.getExpiresIn() != 0) {
            token.setExpiry((System.currentTimeMillis() / 1000L) + token.getExpiresIn());
        }

        return token;
    }

    /**
     * Fetch the OAuth token.
     */
    public OAuthToken fetchToken() throws ApiException, IOException {
        return fetchToken(null);
    }

    /**
     * Refresh the OAuth token.
     * @param additionalParameters Additional parameters to send during token refresh
     */
    public CompletableFuture<OAuthToken> refreshTokenAsync(
            final Map<String, Object> additionalParameters) {

        final Map<String, Object> aparams =
                additionalParameters == null ? new HashMap<String, Object>() : additionalParameters;
        return oAuthApi.refreshTokenOAuthROPCGAsync(
            getBasicAuthForClient(),
            getOAuthToken().getRefreshToken(),
            null,
            aparams).thenApply(token -> {
                return token;
            });
    }

    /**
     * Refresh the OAuth token.
     */
    public CompletableFuture<OAuthToken> refreshTokenAsync() {
        return refreshTokenAsync(null);
    }

    /**
     * Refresh the OAuth token.
     * @param additionalParameters Additional parameters to send during token refresh
     */
    public OAuthToken refreshToken(final Map<String, Object> additionalParameters)
            throws ApiException, IOException {
        final Map<String, Object> aparams =
                additionalParameters == null ? new HashMap<String, Object>() : additionalParameters;
        OAuthToken token = oAuthApi.refreshTokenOAuthROPCG(
            getBasicAuthForClient(),
            getOAuthToken().getRefreshToken(),
            null,
            aparams);

        return token;
    }

    /**
     * Refresh the OAuth token.
     */
    public OAuthToken refreshToken() throws ApiException, IOException {
        return refreshToken(null);
    }

    /**
     * Build authorization header value for basic auth.
     * @return Authorization header value for this client
     */
    private String getBasicAuthForClient() {
        String val = getOAuthClientId() + ":" + getOAuthClientSecret();
        return "Basic " + new String(Base64.getEncoder().encodeToString(val.getBytes()));
    }


    /**
     * Has the OAuth token expired?.
     * @return True if expired
     */
    public boolean isTokenExpired() {
        if (getOAuthToken() == null) {
            throw new IllegalStateException("OAuth token is missing.");
        }

        return getOAuthToken().getExpiry() != null 
            && getOAuthToken().getExpiry() < (System.currentTimeMillis() / 1000L); 
    }

    /**
    * Create authorization header for API calls.
    * @param token OAuth token
    * @return Authorization header
    */
    private static String getAuthorizationHeader(OAuthToken token) {
        if (token == null) {
            return null;
        }
        return "Bearer " + token.getAccessToken();
    }

    /**
    * Validate the authentication on the httpRequest
    */
    @Override
    public void validate() {
        if (getOAuthToken() == null) {
            setErrorMessage("Client is not authorized."
                + " An OAuth token is needed to make API calls.");
            setValidity(false);
        } else if (isTokenExpired()) {
            setErrorMessage("The oAuth token is expired."
                + " A valid token is needed to make API calls.");
            setValidity(false);
        } else {
            setValidity(true);
        }
     }

    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "OAuthROPCG - " + errorMessage;
    }

}
