/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

import localhost3000.models.OAuthToken;

/**
 * A data class for OAuth 2 Resource Owner Credentials Grant credentials.
 */
public class OAuthROPCGModel {
    private String oAuthClientId;
    private String oAuthClientSecret;
    private String oAuthUsername;
    private String oAuthPassword;
    private OAuthToken oAuthToken;

    /**
     * A Constructor for OAuthROPCGModel.
     */
    private OAuthROPCGModel(String oAuthClientId, String oAuthClientSecret, String oAuthUsername,
            String oAuthPassword, OAuthToken oAuthToken) {
        this.oAuthClientId = oAuthClientId;
        this.oAuthClientSecret = oAuthClientSecret;
        this.oAuthUsername = oAuthUsername;
        this.oAuthPassword = oAuthPassword;
        this.oAuthToken = oAuthToken;
    }

    /**
     * Getter for oAuthClientId.
     * @return oAuthClientId The value of OAuthClientId.
     */
    public String getOAuthClientId() {
        return this.oAuthClientId;
    }

    /**
     * Getter for oAuthClientSecret.
     * @return oAuthClientSecret The value of OAuthClientSecret.
     */
    public String getOAuthClientSecret() {
        return this.oAuthClientSecret;
    }

    /**
     * Getter for oAuthUsername.
     * @return oAuthUsername The value of OAuthUsername.
     */
    public String getOAuthUsername() {
        return this.oAuthUsername;
    }

    /**
     * Getter for oAuthPassword.
     * @return oAuthPassword The value of OAuthPassword.
     */
    public String getOAuthPassword() {
        return this.oAuthPassword;
    }

    /**
     * Getter for oAuthToken.
     * @return oAuthToken The value of OAuthToken.
     */
    public OAuthToken getOAuthToken() {
        return this.oAuthToken;
    }

    /**
     * Builds a new {@link OAuthROPCGModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link OAuthROPCGModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getOAuthClientId(), getOAuthClientSecret(), getOAuthUsername(),
                getOAuthPassword())
            .oAuthToken(getOAuthToken());
    }

    /**
     * A Builder class for OAuth 2 Resource Owner Credentials Grant credentials.
     */
    public static class Builder {
        private String oAuthClientId;
        private String oAuthClientSecret;
        private String oAuthUsername;
        private String oAuthPassword;
        private OAuthToken oAuthToken;

        /**
         * The constructor with required auth credentials.
         * @param oAuthClientId The value of OAuthClientId.
         * @param oAuthClientSecret The value of OAuthClientSecret.
         * @param oAuthUsername The value of OAuthUsername.
         * @param oAuthPassword The value of OAuthPassword.
         */
        public Builder(String oAuthClientId, String oAuthClientSecret, String oAuthUsername,
                String oAuthPassword) {
            if (oAuthClientId == null) {
                throw new NullPointerException("OAuthClientId cannot be null.");
            }

            if (oAuthClientSecret == null) {
                throw new NullPointerException("OAuthClientSecret cannot be null.");
            }

            if (oAuthUsername == null) {
                throw new NullPointerException("OAuthUsername cannot be null.");
            }

            if (oAuthPassword == null) {
                throw new NullPointerException("OAuthPassword cannot be null.");
            }

            this.oAuthClientId = oAuthClientId;
            this.oAuthClientSecret = oAuthClientSecret;
            this.oAuthUsername = oAuthUsername;
            this.oAuthPassword = oAuthPassword;
        }

        /**
         * Setter for oAuthClientId.
         * @param oAuthClientId The value of OAuthClientId.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthClientId(String oAuthClientId) {
            if (oAuthClientId == null) {
                throw new NullPointerException("OAuthClientId cannot be null.");
            }

            this.oAuthClientId = oAuthClientId;
            return this;
        }

        /**
         * Setter for oAuthClientSecret.
         * @param oAuthClientSecret The value of OAuthClientSecret.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthClientSecret(String oAuthClientSecret) {
            if (oAuthClientSecret == null) {
                throw new NullPointerException("OAuthClientSecret cannot be null.");
            }

            this.oAuthClientSecret = oAuthClientSecret;
            return this;
        }

        /**
         * Setter for oAuthUsername.
         * @param oAuthUsername The value of OAuthUsername.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthUsername(String oAuthUsername) {
            if (oAuthUsername == null) {
                throw new NullPointerException("OAuthUsername cannot be null.");
            }

            this.oAuthUsername = oAuthUsername;
            return this;
        }

        /**
         * Setter for oAuthPassword.
         * @param oAuthPassword The value of OAuthPassword.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthPassword(String oAuthPassword) {
            if (oAuthPassword == null) {
                throw new NullPointerException("OAuthPassword cannot be null.");
            }

            this.oAuthPassword = oAuthPassword;
            return this;
        }

        /**
         * Setter for oAuthToken.
         * @param oAuthToken The value of OAuthToken.
         * @return Builder The current instance of Builder.
         */
        public Builder oAuthToken(OAuthToken oAuthToken) {
            this.oAuthToken = oAuthToken;
            return this;
        }

        /**
         * Builds the instance of OAuthROPCGModel using the provided credentials.
         * @return The instance of OAuthROPCGModel.
         */
        public OAuthROPCGModel build() {
            return new OAuthROPCGModel(oAuthClientId, oAuthClientSecret, oAuthUsername,
                    oAuthPassword, oAuthToken);
        }
    }
}