/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.authentication;

/**
 * A data class for OAuth 2 Bearer token credentials.
 */
public class OAuthBearerTokenModel {
    private String accessToken;

    /**
     * A Constructor for OAuthBearerTokenModel.
     */
    private OAuthBearerTokenModel(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Getter for accessToken.
     * @return accessToken The value of AccessToken.
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Builds a new {@link OAuthBearerTokenModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link OAuthBearerTokenModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getAccessToken());
    }

    /**
     * A Builder class for OAuth 2 Bearer token credentials.
     */
    public static class Builder {
        private String accessToken;

        /**
         * The constructor with required auth credentials.
         * @param accessToken The value of AccessToken.
         */
        public Builder(String accessToken) {
            if (accessToken == null) {
                throw new NullPointerException("AccessToken cannot be null.");
            }

            this.accessToken = accessToken;
        }

        /**
         * Setter for accessToken.
         * @param accessToken The value of AccessToken.
         * @return Builder The current instance of Builder.
         */
        public Builder accessToken(String accessToken) {
            if (accessToken == null) {
                throw new NullPointerException("AccessToken cannot be null.");
            }

            this.accessToken = accessToken;
            return this;
        }

        /**
         * Builds the instance of OAuthBearerTokenModel using the provided credentials.
         * @return The instance of OAuthBearerTokenModel.
         */
        public OAuthBearerTokenModel build() {
            return new OAuthBearerTokenModel(accessToken);
        }
    }
}