/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.controllers;

import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import localhost3000.ApiHelper;
import localhost3000.Server;
import localhost3000.exceptions.ApiException;
import localhost3000.http.request.HttpMethod;
import localhost3000.models.ServiceStatus;
import localhost3000.models.User;

/**
 * This class lists all the endpoints of the groups.
 */
public final class AuthenticationController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public AuthenticationController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String customAuthentication() throws ApiException, IOException {
        return prepareCustomAuthenticationRequest().execute();
    }

    /**
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> customAuthenticationAsync() {
        try {
            return prepareCustomAuthenticationRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for customAuthentication.
     */
    private ApiCall<String, ApiException> prepareCustomAuthenticationRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/auth/customAuthentication")
                        .withAuth(auth -> auth
                                .add("CustomAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String oAuthBearerToken() throws ApiException, IOException {
        return prepareOAuthBearerTokenRequest().execute();
    }

    /**
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> oAuthBearerTokenAsync() {
        try {
            return prepareOAuthBearerTokenRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for oAuthBearerToken.
     */
    private ApiCall<String, ApiException> prepareOAuthBearerTokenRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/auth/oauth2")
                        .withAuth(auth -> auth
                                .add("OAuthBearerToken"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @return    Returns the ServiceStatus response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ServiceStatus oAuthClientCredentialsGrant() throws ApiException, IOException {
        return prepareOAuthClientCredentialsGrantRequest().execute();
    }

    /**
     * @return    Returns the ServiceStatus response from the API call
     */
    public CompletableFuture<ServiceStatus> oAuthClientCredentialsGrantAsync() {
        try {
            return prepareOAuthClientCredentialsGrantRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for oAuthClientCredentialsGrant.
     */
    private ApiCall<ServiceStatus, ApiException> prepareOAuthClientCredentialsGrantRequest() {
        return new ApiCall.Builder<ServiceStatus, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/non-auth-server/status")
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("OAuthCCG"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, ServiceStatus.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @return    Returns the User response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public User oAuthAuthorizationGrant() throws ApiException, IOException {
        return prepareOAuthAuthorizationGrantRequest().execute();
    }

    /**
     * @return    Returns the User response from the API call
     */
    public CompletableFuture<User> oAuthAuthorizationGrantAsync() {
        try {
            return prepareOAuthAuthorizationGrantRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for oAuthAuthorizationGrant.
     */
    private ApiCall<User, ApiException> prepareOAuthAuthorizationGrantRequest() {
        return new ApiCall.Builder<User, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/non-auth-server/user")
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("OAuthACG")
                                        .add("OAuthROPCG")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, User.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String customQueryOrHeaderAuthentication() throws ApiException, IOException {
        return prepareCustomQueryOrHeaderAuthenticationRequest().execute();
    }

    /**
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> customQueryOrHeaderAuthenticationAsync() {
        try {
            return prepareCustomQueryOrHeaderAuthenticationRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for customQueryOrHeaderAuthentication.
     */
    private ApiCall<String, ApiException> prepareCustomQueryOrHeaderAuthenticationRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/auth/customQueryOrHeaderParam")
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("apiKey")
                                        .add("apiHeader")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String basicAuthAndApiHeaderAuth() throws ApiException, IOException {
        return prepareBasicAuthAndApiHeaderAuthRequest().execute();
    }

    /**
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> basicAuthAndApiHeaderAuthAsync() {
        try {
            return prepareBasicAuthAndApiHeaderAuthRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for basicAuthAndApiHeaderAuth.
     */
    private ApiCall<String, ApiException> prepareBasicAuthAndApiHeaderAuthRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/auth/basicAndApiKeyAndApiHeader")
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("basicAuth")
                                        .add("apiKey")
                                        .add("apiHeader")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint tests or combinations of OAuth types.
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String oAuthGrantTypesORCombinations() throws ApiException, IOException {
        return prepareOAuthGrantTypesORCombinationsRequest().execute();
    }

    /**
     * This endpoint tests or combinations of OAuth types.
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> oAuthGrantTypesORCombinationsAsync() {
        try {
            return prepareOAuthGrantTypesORCombinationsRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for oAuthGrantTypesORCombinations.
     */
    private ApiCall<String, ApiException> prepareOAuthGrantTypesORCombinationsRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/oauthOrCombination")
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuthCCG")
                                        .add("OAuthBearerToken")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint uses globally applied auth which is a hypothetical scneraio but covers the
     * worst case.
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String multipleAuthCombination() throws ApiException, IOException {
        return prepareMultipleAuthCombinationRequest().execute();
    }

    /**
     * This endpoint uses globally applied auth which is a hypothetical scneraio but covers the
     * worst case.
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> multipleAuthCombinationAsync() {
        try {
            return prepareMultipleAuthCombinationRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for multipleAuthCombination.
     */
    private ApiCall<String, ApiException> prepareMultipleAuthCombinationRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/auth/multipleAuthCombination")
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("CustomAuth")
                                        .add("OAuthBearerToken")
                                        .and(andAuth -> andAuth
                                                .add("basicAuth")
                                                .add("apiKey")
                                                .add("apiHeader"))))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This endpoint does not use auth.
     * @deprecated
     *    You should not use this method as it requires no auth and can bring security issues to the server and api call itself!!. This method was deprecated in version 0.0.1-alpha.
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    @Deprecated
    public String noAuth() throws ApiException, IOException {
        return prepareNoAuthRequest().execute();
    }

    /**
     * This endpoint does not use auth.
     * @deprecated
     *    You should not use this method as it requires no auth and can bring security issues to the server and api call itself!!. This method was deprecated in version 0.0.1-alpha.
     * @return    Returns the String response from the API call
     */
    @Deprecated
    public CompletableFuture<String> noAuthAsync() {
        try {
            return prepareNoAuthRequest().executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for noAuth.
     */
    private ApiCall<String, ApiException> prepareNoAuthRequest() {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/auth/noAuth")
                        .queryParam(param -> param.key("array")
                                .value("true").isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}