/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.controllers;

import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import localhost3000.ApiHelper;
import localhost3000.Server;
import localhost3000.exceptions.ApiException;
import localhost3000.exceptions.OAuthProviderException;
import localhost3000.http.request.HttpMethod;
import localhost3000.models.OAuthToken;

/**
 * This class lists all the endpoints of the groups.
 */
public final class OAuthAuthorizationController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public OAuthAuthorizationController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Create a new OAuth 2 token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public OAuthToken requestTokenOAuthCCG(
            final String authorization,
            final String scope,
            final Map<String, Object> fieldParameters) throws ApiException, IOException {
        return prepareRequestTokenOAuthCCGRequest(authorization, scope, fieldParameters).execute();
    }

    /**
     * Create a new OAuth 2 token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     */
    public CompletableFuture<OAuthToken> requestTokenOAuthCCGAsync(
            final String authorization,
            final String scope,
            final Map<String, Object> fieldParameters) {
        try {
            return prepareRequestTokenOAuthCCGRequest(authorization, scope, fieldParameters).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for requestTokenOAuthCCG.
     */
    private ApiCall<OAuthToken, ApiException> prepareRequestTokenOAuthCCGRequest(
            final String authorization,
            final String scope,
            final Map<String, Object> fieldParameters) {
        return new ApiCall.Builder<OAuthToken, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.AUTH.value())
                        .path("/request_token")
                        .formParam(param -> param.key("grant_type")
                                .value("client_credentials").isRequired(false))
                        .formParam(param -> param.key("scope")
                                .value(scope).isRequired(false))
                        .formParam(fieldParameters)
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, OAuthToken.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("OAuth 2 provider returned an error.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("OAuth 2 provider says client authentication failed.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Create a new OAuth 2 token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  code  Required parameter: Authorization Code
     * @param  redirectUri  Required parameter: Redirect Uri
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public OAuthToken requestTokenOAuthACG(
            final String authorization,
            final String code,
            final String redirectUri,
            final Map<String, Object> fieldParameters) throws ApiException, IOException {
        return prepareRequestTokenOAuthACGRequest(authorization, code, redirectUri,
                fieldParameters).execute();
    }

    /**
     * Create a new OAuth 2 token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  code  Required parameter: Authorization Code
     * @param  redirectUri  Required parameter: Redirect Uri
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     */
    public CompletableFuture<OAuthToken> requestTokenOAuthACGAsync(
            final String authorization,
            final String code,
            final String redirectUri,
            final Map<String, Object> fieldParameters) {
        try {
            return prepareRequestTokenOAuthACGRequest(authorization, code, redirectUri,
            fieldParameters).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for requestTokenOAuthACG.
     */
    private ApiCall<OAuthToken, ApiException> prepareRequestTokenOAuthACGRequest(
            final String authorization,
            final String code,
            final String redirectUri,
            final Map<String, Object> fieldParameters) {
        return new ApiCall.Builder<OAuthToken, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/non-auth-server/token")
                        .formParam(param -> param.key("grant_type")
                                .value("authorization_code").isRequired(false))
                        .formParam(param -> param.key("code")
                                .value(code))
                        .formParam(param -> param.key("redirect_uri")
                                .value(redirectUri))
                        .formParam(fieldParameters)
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, OAuthToken.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("OAuth 2 provider returned an error.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("OAuth 2 provider says client authentication failed.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Obtain a new access token using a refresh token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  refreshToken  Required parameter: Refresh token
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public OAuthToken refreshTokenOAuthACG(
            final String authorization,
            final String refreshToken,
            final String scope,
            final Map<String, Object> fieldParameters) throws ApiException, IOException {
        return prepareRefreshTokenOAuthACGRequest(authorization, refreshToken, scope,
                fieldParameters).execute();
    }

    /**
     * Obtain a new access token using a refresh token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  refreshToken  Required parameter: Refresh token
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     */
    public CompletableFuture<OAuthToken> refreshTokenOAuthACGAsync(
            final String authorization,
            final String refreshToken,
            final String scope,
            final Map<String, Object> fieldParameters) {
        try {
            return prepareRefreshTokenOAuthACGRequest(authorization, refreshToken, scope,
            fieldParameters).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for refreshTokenOAuthACG.
     */
    private ApiCall<OAuthToken, ApiException> prepareRefreshTokenOAuthACGRequest(
            final String authorization,
            final String refreshToken,
            final String scope,
            final Map<String, Object> fieldParameters) {
        return new ApiCall.Builder<OAuthToken, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/non-auth-server/token")
                        .formParam(param -> param.key("grant_type")
                                .value("refresh_token").isRequired(false))
                        .formParam(param -> param.key("refresh_token")
                                .value(refreshToken))
                        .formParam(param -> param.key("scope")
                                .value(scope).isRequired(false))
                        .formParam(fieldParameters)
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, OAuthToken.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("OAuth 2 provider returned an error.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("OAuth 2 provider says client authentication failed.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Create a new OAuth 2 token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  username  Required parameter: Resource owner username
     * @param  password  Required parameter: Resource owner password
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public OAuthToken requestTokenOAuthROPCG(
            final String authorization,
            final String username,
            final String password,
            final String scope,
            final Map<String, Object> fieldParameters) throws ApiException, IOException {
        return prepareRequestTokenOAuthROPCGRequest(authorization, username, password, scope,
                fieldParameters).execute();
    }

    /**
     * Create a new OAuth 2 token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  username  Required parameter: Resource owner username
     * @param  password  Required parameter: Resource owner password
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     */
    public CompletableFuture<OAuthToken> requestTokenOAuthROPCGAsync(
            final String authorization,
            final String username,
            final String password,
            final String scope,
            final Map<String, Object> fieldParameters) {
        try {
            return prepareRequestTokenOAuthROPCGRequest(authorization, username, password, scope,
            fieldParameters).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for requestTokenOAuthROPCG.
     */
    private ApiCall<OAuthToken, ApiException> prepareRequestTokenOAuthROPCGRequest(
            final String authorization,
            final String username,
            final String password,
            final String scope,
            final Map<String, Object> fieldParameters) {
        return new ApiCall.Builder<OAuthToken, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/non-auth-server/token")
                        .formParam(param -> param.key("grant_type")
                                .value("password").isRequired(false))
                        .formParam(param -> param.key("username")
                                .value(username))
                        .formParam(param -> param.key("password")
                                .value(password))
                        .formParam(param -> param.key("scope")
                                .value(scope).isRequired(false))
                        .formParam(fieldParameters)
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, OAuthToken.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("OAuth 2 provider returned an error.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("OAuth 2 provider says client authentication failed.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Obtain a new access token using a refresh token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  refreshToken  Required parameter: Refresh token
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public OAuthToken refreshTokenOAuthROPCG(
            final String authorization,
            final String refreshToken,
            final String scope,
            final Map<String, Object> fieldParameters) throws ApiException, IOException {
        return prepareRefreshTokenOAuthROPCGRequest(authorization, refreshToken, scope,
                fieldParameters).execute();
    }

    /**
     * Obtain a new access token using a refresh token.
     * @param  authorization  Required parameter: Authorization header in Basic auth format
     * @param  refreshToken  Required parameter: Refresh token
     * @param  scope  Optional parameter: Requested scopes as a space-delimited list.
     * @param    fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return    Returns the OAuthToken response from the API call
     */
    public CompletableFuture<OAuthToken> refreshTokenOAuthROPCGAsync(
            final String authorization,
            final String refreshToken,
            final String scope,
            final Map<String, Object> fieldParameters) {
        try {
            return prepareRefreshTokenOAuthROPCGRequest(authorization, refreshToken, scope,
            fieldParameters).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for refreshTokenOAuthROPCG.
     */
    private ApiCall<OAuthToken, ApiException> prepareRefreshTokenOAuthROPCGRequest(
            final String authorization,
            final String refreshToken,
            final String scope,
            final Map<String, Object> fieldParameters) {
        return new ApiCall.Builder<OAuthToken, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/oauth2/non-auth-server/token")
                        .formParam(param -> param.key("grant_type")
                                .value("refresh_token").isRequired(false))
                        .formParam(param -> param.key("refresh_token")
                                .value(refreshToken))
                        .formParam(param -> param.key("scope")
                                .value(scope).isRequired(false))
                        .formParam(fieldParameters)
                        .headerParam(param -> param.key("Authorization")
                                .value(authorization).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, OAuthToken.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("OAuth 2 provider returned an error.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("OAuth 2 provider says client authentication failed.",
                                (reason, context) -> new OAuthProviderException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}