/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import io.apimatic.core.utilities.TestHelper;
import localhost3000.MultiAuthSampleClient;
import localhost3000.exceptions.ApiException;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class AuthenticationControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static MultiAuthSampleClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static AuthenticationController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getAuthenticationController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Test case for Custom Authentication.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testCustomAuthenticationTest() throws Exception {

        // Set callback and perform API call
        String result = null;
        try {
            result = controller.customAuthentication();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "You've passed the test!",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

    /**
     * Test case for OAuth Bearer Token.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testOAuth2Test() throws Exception {

        // Set callback and perform API call
        String result = null;
        try {
            result = controller.oAuthBearerToken();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "You've passed the test!",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

    /**
     * Test case for OAuth Client Credentials Grant.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testCheckServiceStatus() throws Exception {

        // Set callback and perform API call
        try {
            controller.oAuthClientCredentialsGrant();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Test case for Custom Query Or Header Authentication.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testCustomQueryParamTest() throws Exception {

        // Set callback and perform API call
        String result = null;
        try {
            result = controller.customQueryOrHeaderAuthentication();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "You've passed the test!",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

    /**
     * Test case for Basic Auth And Api/Header Auth.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testBasicAuthAndApiKeyAndApiHeader() throws Exception {

        // Set callback and perform API call
        String result = null;
        try {
            result = controller.basicAuthAndApiHeaderAuth();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "You've passed the test!",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

    /**
     * Test case for OAuth Grant Types OR Combinations.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testOAuthOrCombinationTest() throws Exception {

        // Set callback and perform API call
        String result = null;
        try {
            result = controller.oAuthGrantTypesORCombinations();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "You've passed the test!",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

    /**
     * Test case for Multiple Auth Combination.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testMultipleAuthOrCombinationTest() throws Exception {

        // Set callback and perform API call
        String result = null;
        try {
            result = controller.multipleAuthCombination();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "You've passed the test!",
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

}
