/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.controllers;

import localhost3000.Environment;
import localhost3000.MultiAuthSampleClient;
import localhost3000.authentication.ApiHeaderModel;
import localhost3000.authentication.ApiKeyModel;
import localhost3000.authentication.BasicAuthModel;
import localhost3000.authentication.OAuthACGModel;
import localhost3000.authentication.OAuthBearerTokenModel;
import localhost3000.authentication.OAuthCCGModel;
import localhost3000.authentication.OAuthROPCGModel;
import localhost3000.models.OAuthToken;
import localhost3000.models.SuiteCodeEnum;
import localhost3000.testing.HttpCallbackCatcher;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.rules.Timeout;

/**
 * Base class for all test cases.
 */
public class BaseControllerTest {
    /**
     * Test configuration.
     */
    public static final int REQUEST_TIMEOUT = 30;

    public static final double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests.
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures,
     * Used to serve as HttpCallback and to capture request & response.
     */

    protected static HttpCallbackCatcher httpResponse;
    
    /**
     * Setup test.
     */
    @BeforeClass
    public static void setUp() throws Exception {
        httpResponse = new HttpCallbackCatcher(); 
    }

    /**
     * Tear down test.
     */
    @AfterClass
    public static void tearDown() throws Exception {
        httpResponse = null;
    }

    /**
     * Create test configuration from Environment variables.
     */
    protected static MultiAuthSampleClient createConfigurationFromEnvironment() {
        MultiAuthSampleClient.Builder builder = new MultiAuthSampleClient.Builder();

        final String environment = System.getenv("MULTI_AUTH_SAMPLE_LIB_ENVIRONMENT");
        final String port = System.getenv("MULTI_AUTH_SAMPLE_LIB_PORT");
        final String suites = System.getenv("MULTI_AUTH_SAMPLE_LIB_SUITES");
        final String accessToken2 = System.getenv("MULTI_AUTH_SAMPLE_LIB_ACCESS_TOKEN_2");
        final String timeout = System.getenv("MULTI_AUTH_SAMPLE_LIB_TIMEOUT");
        final String username = System.getenv("MULTI_AUTH_SAMPLE_LIB_USERNAME");
        final String password = System.getenv("MULTI_AUTH_SAMPLE_LIB_PASSWORD");
        final String token = System.getenv("MULTI_AUTH_SAMPLE_LIB_TOKEN");
        final String apiKey = System.getenv("MULTI_AUTH_SAMPLE_LIB_API_KEY");
        final String token2 = System.getenv("MULTI_AUTH_SAMPLE_LIB_TOKEN_2");
        final String apiKey2 = System.getenv("MULTI_AUTH_SAMPLE_LIB_API_KEY_2");
        final String oAuthClientId = System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_ID");
        final String oAuthClientSecret =
                System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_SECRET");
        final String oAuthClientId2 = System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_ID_2");
        final String oAuthClientSecret2 =
                System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_SECRET_2");
        final String oAuthRedirectUri2 =
                System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_REDIRECT_URI_2");
        final String oAuthClientId3 = System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_ID_3");
        final String oAuthClientSecret3 =
                System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_CLIENT_SECRET_3");
        final String oAuthUsername3 = System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_USERNAME_3");
        final String oAuthPassword3 = System.getenv("MULTI_AUTH_SAMPLE_LIB_O_AUTH_PASSWORD_3");
        final String accessToken = System.getenv("MULTI_AUTH_SAMPLE_LIB_ACCESS_TOKEN");

        if (username != null && password != null) {
            builder.basicAuthCredentials(new BasicAuthModel
                    .Builder(username, password)
                    .build());
        }
        if (token != null && apiKey != null) {
            builder.apiKeyCredentials(new ApiKeyModel
                    .Builder(token, apiKey)
                    .build());
        }
        if (token2 != null && apiKey2 != null) {
            builder.apiHeaderCredentials(new ApiHeaderModel
                    .Builder(token2, apiKey2)
                    .build());
        }
        if (oAuthClientId != null && oAuthClientSecret != null) {
            builder.oAuthCCGCredentials(new OAuthCCGModel
                    .Builder(oAuthClientId, oAuthClientSecret)
                    .build());
        }
        if (oAuthClientId2 != null && oAuthClientSecret2 != null && oAuthRedirectUri2 != null) {
            builder.oAuthACGCredentials(new OAuthACGModel
                    .Builder(oAuthClientId2, oAuthClientSecret2, oAuthRedirectUri2)
                    .build());
        }
        if (oAuthClientId3 != null && oAuthClientSecret3 != null && oAuthUsername3 != null && oAuthPassword3 != null) {
            builder.oAuthROPCGCredentials(new OAuthROPCGModel
                    .Builder(oAuthClientId3, oAuthClientSecret3, oAuthUsername3, oAuthPassword3)
                    .build());
        }
        if (accessToken != null) {
            builder.oAuthBearerTokenCredentials(new OAuthBearerTokenModel
                    .Builder(accessToken)
                    .build());
        }
        if (environment != null) {
            builder.environment(Environment.fromString(environment));
        }
        if (port != null) {
            builder.port(port);
        }
        if (suites != null) {
            builder.suites(SuiteCodeEnum.fromInteger(Integer.parseInt(suites)));
        }
        if (accessToken2 != null) {
            builder.accessToken2(accessToken2);
        }
        if (timeout != null) {
            builder.httpClientConfig(configBuilder -> configBuilder.timeout(
                    Long.parseLong(timeout)));
        }
        return builder.build();
    }

    /**
     * Create test configuration.
     */
    protected static MultiAuthSampleClient createConfiguration() {
        // Set Configuration parameters for test execution
        MultiAuthSampleClient config = createConfigurationFromEnvironment();
        config = config.newBuilder()
                .basicAuthCredentials(new BasicAuthModel
                        .Builder("Zeeshan", "bhai_99").build())
                .apiKeyCredentials(new ApiKeyModel
                        .Builder("asdqwaxr2gSdhasWSDbdAgdA637sdAhde7Adysi23", "api-key").build())
                .apiHeaderCredentials(new ApiHeaderModel
                        .Builder("Qaws2W233WedeRe4T56G6Vref2", "api-key").build())
                .oAuthCCGCredentials(new OAuthCCGModel
                        .Builder("23", "tQNSqQlXBIwZcY9auoujQ57ckDcoh3t8UPbBRkSF").build())
                .oAuthACGCredentials(new OAuthACGModel
                        .Builder("24", "Y9auoujQ57ckDtQNSqQlXBIwZccoh3t8UPbBRkSF", "x").build())
                .oAuthROPCGCredentials(new OAuthROPCGModel
                        .Builder("25", "ckDcoh3t8UPbBRkSFtQNSqQlXBIwZcY9auoujQ57", "apimatic",
                                "api-d604257e42-matic").build())
                .oAuthBearerTokenCredentials(new OAuthBearerTokenModel
                        .Builder("0b79bab50daca910b000d4f1a2b675d604257e42").build())
                .accessToken2("azHmdOe09EdchxeWsdnplkQbv76sJH")
                .httpCallback(httpResponse)
                .build();

        try {
            OAuthToken token = config.getOAuthACGCredentials().fetchToken("910b000d4f");
            config = config.newBuilder()
                .oAuthACGCredentials(config.getOAuthACGModel()
                        .toBuilder()
                        .oAuthToken(token)
                        .build())
                .build();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        try {
            OAuthToken token = config.getOAuthROPCGCredentials().fetchToken();
            config = config.newBuilder()
                .oAuthROPCGCredentials(config.getOAuthROPCGModel()
                        .toBuilder()
                        .oAuthToken(token)
                        .build())
                .build();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return config;
    }
}
