/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000;

import localhost3000.authentication.ApiHeaderCredentials;
import localhost3000.authentication.ApiHeaderModel;
import localhost3000.authentication.ApiKeyCredentials;
import localhost3000.authentication.ApiKeyModel;
import localhost3000.authentication.BasicAuthCredentials;
import localhost3000.authentication.BasicAuthModel;
import localhost3000.authentication.OAuthACGCredentials;
import localhost3000.authentication.OAuthACGModel;
import localhost3000.authentication.OAuthBearerTokenCredentials;
import localhost3000.authentication.OAuthBearerTokenModel;
import localhost3000.authentication.OAuthCCGCredentials;
import localhost3000.authentication.OAuthCCGModel;
import localhost3000.authentication.OAuthROPCGCredentials;
import localhost3000.authentication.OAuthROPCGModel;
import localhost3000.http.client.ReadonlyHttpClientConfiguration;
import localhost3000.models.SuiteCodeEnum;

/**
 * Configuration Interface for the library.
 */
public interface Configuration {

    /**
     * Current API environment.
     * @return a copy of environment
     */
    Environment getEnvironment();

    /**
     * port value.
     * @return a copy of port
     */
    String getPort();

    /**
     * suites value.
     * @return a copy of suites
     */
    SuiteCodeEnum getSuites();

    /**
     * .
     * @return a copy of accessToken2
     */
    String getAccessToken2();

    /**
     * Http Client Configuration instance.
     * @return a copy of httpClientConfig
     */
    ReadonlyHttpClientConfiguration getHttpClientConfig();

    /**
     * The timeout to use for making HTTP requests. The timeout to use for making HTTP requests.
     * @return a copy of timeout
     */
    long timeout();

    /**
     * The credentials to use with BasicAuth.
     * @return basicAuthCredentials
     */
    BasicAuthCredentials getBasicAuthCredentials();

    /**
     * The auth credential model for BasicAuth.
     * @return the instance of BasicAuthModel
     */
    BasicAuthModel getBasicAuthModel();

    /**
     * The credentials to use with ApiKey.
     * @return apiKeyCredentials
     */
    ApiKeyCredentials getApiKeyCredentials();

    /**
     * The auth credential model for ApiKey.
     * @return the instance of ApiKeyModel
     */
    ApiKeyModel getApiKeyModel();

    /**
     * The credentials to use with ApiHeader.
     * @return apiHeaderCredentials
     */
    ApiHeaderCredentials getApiHeaderCredentials();

    /**
     * The auth credential model for ApiHeader.
     * @return the instance of ApiHeaderModel
     */
    ApiHeaderModel getApiHeaderModel();

    /**
     * The credentials to use with OAuthCCG.
     * @return oAuthCCGCredentials
     */
    OAuthCCGCredentials getOAuthCCGCredentials();

    /**
     * The auth credential model for OAuthCCG.
     * @return the instance of OAuthCCGModel
     */
    OAuthCCGModel getOAuthCCGModel();

    /**
     * The credentials to use with OAuthACG.
     * @return oAuthACGCredentials
     */
    OAuthACGCredentials getOAuthACGCredentials();

    /**
     * The auth credential model for OAuthACG.
     * @return the instance of OAuthACGModel
     */
    OAuthACGModel getOAuthACGModel();

    /**
     * The credentials to use with OAuthROPCG.
     * @return oAuthROPCGCredentials
     */
    OAuthROPCGCredentials getOAuthROPCGCredentials();

    /**
     * The auth credential model for OAuthROPCG.
     * @return the instance of OAuthROPCGModel
     */
    OAuthROPCGModel getOAuthROPCGModel();

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken
     */
    String getAccessToken();

    /**
     * The credentials to use with OAuthBearerToken.
     * @return oAuthBearerTokenCredentials
     */
    OAuthBearerTokenCredentials getOAuthBearerTokenCredentials();

    /**
     * The auth credential model for OAuthBearerToken.
     * @return the instance of OAuthBearerTokenModel
     */
    OAuthBearerTokenModel getOAuthBearerTokenModel();

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    String getBaseUri(Server server);

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    String getBaseUri();
}
