/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000;

import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;
import localhost3000.authentication.ApiHeaderCredentials;
import localhost3000.authentication.ApiHeaderManager;
import localhost3000.authentication.ApiHeaderModel;
import localhost3000.authentication.ApiKeyCredentials;
import localhost3000.authentication.ApiKeyManager;
import localhost3000.authentication.ApiKeyModel;
import localhost3000.authentication.BasicAuthCredentials;
import localhost3000.authentication.BasicAuthManager;
import localhost3000.authentication.BasicAuthModel;
import localhost3000.authentication.CustomAuthManager;
import localhost3000.authentication.OAuthACGCredentials;
import localhost3000.authentication.OAuthACGManager;
import localhost3000.authentication.OAuthACGModel;
import localhost3000.authentication.OAuthBearerTokenCredentials;
import localhost3000.authentication.OAuthBearerTokenManager;
import localhost3000.authentication.OAuthBearerTokenModel;
import localhost3000.authentication.OAuthCCGCredentials;
import localhost3000.authentication.OAuthCCGManager;
import localhost3000.authentication.OAuthCCGModel;
import localhost3000.authentication.OAuthROPCGCredentials;
import localhost3000.authentication.OAuthROPCGManager;
import localhost3000.authentication.OAuthROPCGModel;
import localhost3000.controllers.AuthenticationController;
import localhost3000.controllers.OAuthAuthorizationController;
import localhost3000.http.client.HttpCallback;
import localhost3000.http.client.HttpClientConfiguration;
import localhost3000.http.client.ReadonlyHttpClientConfiguration;
import localhost3000.models.SuiteCodeEnum;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class MultiAuthSampleClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private AuthenticationController authentication;
    private OAuthAuthorizationController oAuthAuthorization;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "APIMATIC 3.0";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * port value.
     */
    private final String port;

    /**
     * suites value.
     */
    private final SuiteCodeEnum suites;

    /**
     * .
     */
    private final String accessToken2;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * BasicAuthManager.
     */
    private BasicAuthManager basicAuthManager;

    /**
     * The instance of BasicAuthModel.
     */
    private BasicAuthModel basicAuthModel;

    /**
     * ApiKeyManager.
     */
    private ApiKeyManager apiKeyManager;

    /**
     * The instance of ApiKeyModel.
     */
    private ApiKeyModel apiKeyModel;

    /**
     * ApiHeaderManager.
     */
    private ApiHeaderManager apiHeaderManager;

    /**
     * The instance of ApiHeaderModel.
     */
    private ApiHeaderModel apiHeaderModel;

    /**
     * OAuthCCGManager.
     */
    private OAuthCCGManager oAuthCCGManager;

    /**
     * The instance of OAuthCCGModel.
     */
    private OAuthCCGModel oAuthCCGModel;

    /**
     * OAuthACGManager.
     */
    private OAuthACGManager oAuthACGManager;

    /**
     * The instance of OAuthACGModel.
     */
    private OAuthACGModel oAuthACGModel;

    /**
     * OAuthROPCGManager.
     */
    private OAuthROPCGManager oAuthROPCGManager;

    /**
     * The instance of OAuthROPCGModel.
     */
    private OAuthROPCGModel oAuthROPCGModel;

    /**
     * OAuthBearerTokenManager.
     */
    private OAuthBearerTokenManager oAuthBearerTokenManager;

    /**
     * The instance of OAuthBearerTokenModel.
     */
    private OAuthBearerTokenModel oAuthBearerTokenModel;

    /**
     * CustomAuthManager.
     */
    private CustomAuthManager customAuthManager;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private MultiAuthSampleClient(Environment environment, String port, SuiteCodeEnum suites,
            String accessToken2, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, BasicAuthModel basicAuthModel,
            ApiKeyModel apiKeyModel, ApiHeaderModel apiHeaderModel, OAuthCCGModel oAuthCCGModel,
            OAuthACGModel oAuthACGModel, OAuthROPCGModel oAuthROPCGModel,
            OAuthBearerTokenModel oAuthBearerTokenModel, HttpCallback httpCallback) {
        this.environment = environment;
        this.port = port;
        this.suites = suites;
        this.accessToken2 = accessToken2;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;

        this.basicAuthModel = basicAuthModel;
        this.apiKeyModel = apiKeyModel;
        this.apiHeaderModel = apiHeaderModel;
        this.oAuthCCGModel = oAuthCCGModel;
        this.oAuthACGModel = oAuthACGModel;
        this.oAuthROPCGModel = oAuthROPCGModel;
        this.oAuthBearerTokenModel = oAuthBearerTokenModel;

        this.basicAuthManager = new BasicAuthManager(basicAuthModel);
        this.authentications.put("basicAuth", basicAuthManager);

        this.apiKeyManager = new ApiKeyManager(apiKeyModel);
        this.authentications.put("apiKey", apiKeyManager);

        this.apiHeaderManager = new ApiHeaderManager(apiHeaderModel);
        this.authentications.put("apiHeader", apiHeaderManager);

        this.oAuthCCGManager = new OAuthCCGManager(oAuthCCGModel);
        this.authentications.put("OAuthCCG", oAuthCCGManager);

        this.oAuthACGManager = new OAuthACGManager(oAuthACGModel);
        this.authentications.put("OAuthACG", oAuthACGManager);

        this.oAuthROPCGManager = new OAuthROPCGManager(oAuthROPCGModel);
        this.authentications.put("OAuthROPCG", oAuthROPCGManager);

        this.oAuthBearerTokenManager = new OAuthBearerTokenManager(oAuthBearerTokenModel);
        this.authentications.put("OAuthBearerToken", oAuthBearerTokenManager);

        this.customAuthManager = new CustomAuthManager(this);
        this.authentications.put("CustomAuth", customAuthManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .globalHeader("accessToken", accessToken2)
                .build();
        this.oAuthCCGManager.applyGlobalConfiguration(globalConfig);
        this.oAuthACGManager.applyGlobalConfiguration(globalConfig);
        this.oAuthROPCGManager.applyGlobalConfiguration(globalConfig);

        authentication = new AuthenticationController(globalConfig);
        oAuthAuthorization = new OAuthAuthorizationController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of AuthenticationController.
     * @return authentication
     */
    public AuthenticationController getAuthenticationController() {
        return authentication;
    }

    /**
     * Get the instance of OAuthAuthorizationController.
     * @return oAuthAuthorization
     */
    public OAuthAuthorizationController getOAuthAuthorizationController() {
        return oAuthAuthorization;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * port value.
     * @return port
     */
    public String getPort() {
        return port;
    }

    /**
     * suites value.
     * @return suites
     */
    public SuiteCodeEnum getSuites() {
        return suites;
    }

    /**
     * .
     * @return accessToken2
     */
    public String getAccessToken2() {
        return accessToken2;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with BasicAuth.
     * @return basicAuthCredentials
     */
    public BasicAuthCredentials getBasicAuthCredentials() {
        return basicAuthManager;
    }

    /**
     * The auth credential model for BasicAuth.
     * @return the instance of BasicAuthModel
     */
    public BasicAuthModel getBasicAuthModel() {
        return basicAuthModel;
    }
    /**
     * The credentials to use with ApiKey.
     * @return apiKeyCredentials
     */
    public ApiKeyCredentials getApiKeyCredentials() {
        return apiKeyManager;
    }

    /**
     * The auth credential model for ApiKey.
     * @return the instance of ApiKeyModel
     */
    public ApiKeyModel getApiKeyModel() {
        return apiKeyModel;
    }
    /**
     * The credentials to use with ApiHeader.
     * @return apiHeaderCredentials
     */
    public ApiHeaderCredentials getApiHeaderCredentials() {
        return apiHeaderManager;
    }

    /**
     * The auth credential model for ApiHeader.
     * @return the instance of ApiHeaderModel
     */
    public ApiHeaderModel getApiHeaderModel() {
        return apiHeaderModel;
    }
    /**
     * The credentials to use with OAuthCCG.
     * @return oAuthCCGCredentials
     */
    public OAuthCCGCredentials getOAuthCCGCredentials() {
        return oAuthCCGManager;
    }

    /**
     * The auth credential model for OAuthCCG.
     * @return the instance of OAuthCCGModel
     */
    public OAuthCCGModel getOAuthCCGModel() {
        return oAuthCCGModel;
    }
    /**
     * The credentials to use with OAuthACG.
     * @return oAuthACGCredentials
     */
    public OAuthACGCredentials getOAuthACGCredentials() {
        return oAuthACGManager;
    }

    /**
     * The auth credential model for OAuthACG.
     * @return the instance of OAuthACGModel
     */
    public OAuthACGModel getOAuthACGModel() {
        return oAuthACGModel;
    }
    /**
     * The credentials to use with OAuthROPCG.
     * @return oAuthROPCGCredentials
     */
    public OAuthROPCGCredentials getOAuthROPCGCredentials() {
        return oAuthROPCGManager;
    }

    /**
     * The auth credential model for OAuthROPCG.
     * @return the instance of OAuthROPCGModel
     */
    public OAuthROPCGModel getOAuthROPCGModel() {
        return oAuthROPCGModel;
    }
    /**
     * The credentials to use with OAuthBearerToken.
     * @return oAuthBearerTokenCredentials
     */
    public OAuthBearerTokenCredentials getOAuthBearerTokenCredentials() {
        return oAuthBearerTokenManager;
    }

    /**
     * The auth credential model for OAuthBearerToken.
     * @return the instance of OAuthBearerTokenModel
     */
    public OAuthBearerTokenModel getOAuthBearerTokenModel() {
        return oAuthBearerTokenModel;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken
     */
    public String getAccessToken() {
        return getOAuthBearerTokenCredentials().getAccessToken();
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        parameters.put("port",
                new SimpleEntry<Object, Boolean>(this.port, false));
        parameters.put("suites",
                new SimpleEntry<Object, Boolean>(this.suites, false));
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "http://apimatic.hopto.org:{suites}";
            }
            if (server.equals(Server.AUTH)) {
                return "http://apimaticauth.hopto.org:3000";
            }
        }
        if (environment.equals(Environment.TESTING)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "http://localhost:3000";
            }
            if (server.equals(Server.AUTH)) {
                return "http://localhost:3000/oauth2/auth-server";
            }
        }
        return "http://localhost:3000";
    }

    /**
     * Converts this MultiAuthSampleClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MultiAuthSampleClient [" + "environment=" + environment + ", port=" + port
                + ", suites=" + suites + ", accessToken2=" + accessToken2 + ", httpClientConfig="
                + httpClientConfig + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link MultiAuthSampleClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link MultiAuthSampleClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.port = getPort();
        builder.suites = getSuites();
        builder.accessToken2 = getAccessToken2();
        builder.httpClient = getHttpClient();
        builder.basicAuthCredentials(getBasicAuthModel()
                .toBuilder().build());
        builder.apiKeyCredentials(getApiKeyModel()
                .toBuilder().build());
        builder.apiHeaderCredentials(getApiHeaderModel()
                .toBuilder().build());
        builder.oAuthCCGCredentials(getOAuthCCGModel()
                .toBuilder().build());
        builder.oAuthACGCredentials(getOAuthACGModel()
                .toBuilder().build());
        builder.oAuthROPCGCredentials(getOAuthROPCGModel()
                .toBuilder().build());
        builder.oAuthBearerTokenCredentials(getOAuthBearerTokenModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link MultiAuthSampleClient}.
     */
    public static class Builder {

        private Environment environment = Environment.TESTING;
        private String port = "80";
        private SuiteCodeEnum suites = SuiteCodeEnum.HEARTS;
        private String accessToken2 = "";
        private HttpClient httpClient;
        private BasicAuthModel basicAuthModel = new BasicAuthModel.Builder("", "").build();
        private ApiKeyModel apiKeyModel = new ApiKeyModel.Builder("", "").build();
        private ApiHeaderModel apiHeaderModel = new ApiHeaderModel.Builder("", "").build();
        private OAuthCCGModel oAuthCCGModel = new OAuthCCGModel.Builder("", "").build();
        private OAuthACGModel oAuthACGModel = new OAuthACGModel.Builder("", "", "").build();
        private OAuthROPCGModel oAuthROPCGModel =
                new OAuthROPCGModel.Builder("", "", "", "").build();
        private OAuthBearerTokenModel oAuthBearerTokenModel =
                new OAuthBearerTokenModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for BasicAuthCredentials.
         * @param basicAuthModel The instance of BasicAuthModel.
         * @return The current instance of builder.
         */
        public Builder basicAuthCredentials(BasicAuthModel basicAuthModel) {
            this.basicAuthModel = basicAuthModel;
            return this;
        }

        /**
         * Credentials setter for ApiKeyCredentials.
         * @param apiKeyModel The instance of ApiKeyModel.
         * @return The current instance of builder.
         */
        public Builder apiKeyCredentials(ApiKeyModel apiKeyModel) {
            this.apiKeyModel = apiKeyModel;
            return this;
        }

        /**
         * Credentials setter for ApiHeaderCredentials.
         * @param apiHeaderModel The instance of ApiHeaderModel.
         * @return The current instance of builder.
         */
        public Builder apiHeaderCredentials(ApiHeaderModel apiHeaderModel) {
            this.apiHeaderModel = apiHeaderModel;
            return this;
        }

        /**
         * Credentials setter for OAuthCCGCredentials.
         * @param oAuthCCGModel The instance of OAuthCCGModel.
         * @return The current instance of builder.
         */
        public Builder oAuthCCGCredentials(OAuthCCGModel oAuthCCGModel) {
            this.oAuthCCGModel = oAuthCCGModel;
            return this;
        }

        /**
         * Credentials setter for OAuthACGCredentials.
         * @param oAuthACGModel The instance of OAuthACGModel.
         * @return The current instance of builder.
         */
        public Builder oAuthACGCredentials(OAuthACGModel oAuthACGModel) {
            this.oAuthACGModel = oAuthACGModel;
            return this;
        }

        /**
         * Credentials setter for OAuthROPCGCredentials.
         * @param oAuthROPCGModel The instance of OAuthROPCGModel.
         * @return The current instance of builder.
         */
        public Builder oAuthROPCGCredentials(OAuthROPCGModel oAuthROPCGModel) {
            this.oAuthROPCGModel = oAuthROPCGModel;
            return this;
        }

        /**
         * Credentials setter for OAuthBearerTokenCredentials.
         * @param oAuthBearerTokenModel The instance of OAuthBearerTokenModel.
         * @return The current instance of builder.
         */
        public Builder oAuthBearerTokenCredentials(OAuthBearerTokenModel oAuthBearerTokenModel) {
            this.oAuthBearerTokenModel = oAuthBearerTokenModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * port value.
         * @param port The port for client.
         * @return Builder
         */
        public Builder port(String port) {
            this.port = port;
            return this;
        }

        /**
         * suites value.
         * @param suites The suites for client.
         * @return Builder
         */
        public Builder suites(SuiteCodeEnum suites) {
            this.suites = suites;
            return this;
        }

        /**
         * .
         * @param accessToken2 The accessToken2 for client.
         * @return Builder
         */
        public Builder accessToken2(String accessToken2) {
            if (accessToken2 == null) {
                throw new NullPointerException("accessToken2 cannot be null");
            }
            this.accessToken2 = accessToken2;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new MultiAuthSampleClient object using the set fields.
         * @return MultiAuthSampleClient
         */
        public MultiAuthSampleClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new MultiAuthSampleClient(environment, port, suites, accessToken2, httpClient,
                    httpClientConfig, basicAuthModel, apiKeyModel, apiHeaderModel, oAuthCCGModel,
                    oAuthACGModel, oAuthROPCGModel, oAuthBearerTokenModel, httpCallback);
        }
    }
}