/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for ServiceStatus type.
 */
public class ServiceStatus
        extends BaseModel {
    private String app;
    private String moto;
    private Integer notes;
    private Integer users;
    private String time;
    private String os;
    private String phpVersion;
    private String status;

    /**
     * Default constructor.
     */
    public ServiceStatus() {
    }

    /**
     * Initialization constructor.
     * @param  status  String value for status.
     * @param  app  String value for app.
     * @param  moto  String value for moto.
     * @param  notes  Integer value for notes.
     * @param  users  Integer value for users.
     * @param  time  String value for time.
     * @param  os  String value for os.
     * @param  phpVersion  String value for phpVersion.
     */
    public ServiceStatus(
            String status,
            String app,
            String moto,
            Integer notes,
            Integer users,
            String time,
            String os,
            String phpVersion) {
        this.app = app;
        this.moto = moto;
        this.notes = notes;
        this.users = users;
        this.time = time;
        this.os = os;
        this.phpVersion = phpVersion;
        this.status = status;
    }

    /**
     * Getter for App.
     * @return Returns the String
     */
    @JsonGetter("app")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getApp() {
        return app;
    }

    /**
     * Setter for App.
     * @param app Value for String
     */
    @JsonSetter("app")
    public void setApp(String app) {
        this.app = app;
    }

    /**
     * Getter for Moto.
     * @return Returns the String
     */
    @JsonGetter("moto")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMoto() {
        return moto;
    }

    /**
     * Setter for Moto.
     * @param moto Value for String
     */
    @JsonSetter("moto")
    public void setMoto(String moto) {
        this.moto = moto;
    }

    /**
     * Getter for Notes.
     * @return Returns the Integer
     */
    @JsonGetter("notes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNotes() {
        return notes;
    }

    /**
     * Setter for Notes.
     * @param notes Value for Integer
     */
    @JsonSetter("notes")
    public void setNotes(Integer notes) {
        this.notes = notes;
    }

    /**
     * Getter for Users.
     * @return Returns the Integer
     */
    @JsonGetter("users")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUsers() {
        return users;
    }

    /**
     * Setter for Users.
     * @param users Value for Integer
     */
    @JsonSetter("users")
    public void setUsers(Integer users) {
        this.users = users;
    }

    /**
     * Getter for Time.
     * @return Returns the String
     */
    @JsonGetter("time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTime() {
        return time;
    }

    /**
     * Setter for Time.
     * @param time Value for String
     */
    @JsonSetter("time")
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * Getter for Os.
     * @return Returns the String
     */
    @JsonGetter("os")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOs() {
        return os;
    }

    /**
     * Setter for Os.
     * @param os Value for String
     */
    @JsonSetter("os")
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * Getter for PhpVersion.
     * @return Returns the String
     */
    @JsonGetter("php_version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPhpVersion() {
        return phpVersion;
    }

    /**
     * Setter for PhpVersion.
     * @param phpVersion Value for String
     */
    @JsonSetter("php_version")
    public void setPhpVersion(String phpVersion) {
        this.phpVersion = phpVersion;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Converts this ServiceStatus into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ServiceStatus [" + "status=" + status + ", app=" + app + ", moto=" + moto
                + ", notes=" + notes + ", users=" + users + ", time=" + time + ", os=" + os
                + ", phpVersion=" + phpVersion + ", additionalProperties="
                + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link ServiceStatus.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ServiceStatus.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status)
                .app(getApp())
                .moto(getMoto())
                .notes(getNotes())
                .users(getUsers())
                .time(getTime())
                .os(getOs())
                .phpVersion(getPhpVersion());
        return builder;
    }

    /**
     * Class to build instances of {@link ServiceStatus}.
     */
    public static class Builder {
        private String status;
        private String app;
        private String moto;
        private Integer notes;
        private Integer users;
        private String time;
        private String os;
        private String phpVersion;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  String value for status.
         */
        public Builder(String status) {
            this.status = status;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for app.
         * @param  app  String value for app.
         * @return Builder
         */
        public Builder app(String app) {
            this.app = app;
            return this;
        }

        /**
         * Setter for moto.
         * @param  moto  String value for moto.
         * @return Builder
         */
        public Builder moto(String moto) {
            this.moto = moto;
            return this;
        }

        /**
         * Setter for notes.
         * @param  notes  Integer value for notes.
         * @return Builder
         */
        public Builder notes(Integer notes) {
            this.notes = notes;
            return this;
        }

        /**
         * Setter for users.
         * @param  users  Integer value for users.
         * @return Builder
         */
        public Builder users(Integer users) {
            this.users = users;
            return this;
        }

        /**
         * Setter for time.
         * @param  time  String value for time.
         * @return Builder
         */
        public Builder time(String time) {
            this.time = time;
            return this;
        }

        /**
         * Setter for os.
         * @param  os  String value for os.
         * @return Builder
         */
        public Builder os(String os) {
            this.os = os;
            return this;
        }

        /**
         * Setter for phpVersion.
         * @param  phpVersion  String value for phpVersion.
         * @return Builder
         */
        public Builder phpVersion(String phpVersion) {
            this.phpVersion = phpVersion;
            return this;
        }

        /**
         * Builds a new {@link ServiceStatus} object using the set fields.
         * @return {@link ServiceStatus}
         */
        public ServiceStatus build() {
            return new ServiceStatus(status, app, moto, notes, users, time, os, phpVersion);
        }
    }
}
